const mix = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.styles([
    'resources/assets/css/bootstrap.min.css',
    'resources/assets/css/all.min.css',
    'resources/assets/css/nprogress.css',
    'resources/assets/css/jquery.mCustomScrollbar.min.css',
    'resources/assets/css/green.css',
    'resources/assets/css/prettify.min.css',
    'resources/assets/css/select2.min.css',
    'resources/assets/css/switchery.min.css',
    'resources/assets/css/starrr.css',
    'resources/assets/css/daterangepiker.css',
    'resources/assets/css/dropzone.min.css',
    'resources/assets/css/custom.min.css',
    'resources/assets/css/core/main.css',
    'resources/assets/css/daygrid/main.css',
    'resources/assets/css/timegrid/main.css',
    'resources/assets/css/bootstrap-select.min.css',
    'resources/assets/css/dataTables.bootstrap.min.css',
    'resources/assets/css/buttons.bootstrap.min.css',
    'resources/assets/css/fixedHeader.boottrap.min.css',
    'resources/assets/css/responsive.bootstrap.min.css',
    'resources/assets/css/scroller.bootstrap.min.css',
    'resources/assets/css/jqvmap.min.css',
    'resources/assets/css/bootstrap-progressbar-3.3.4.min.css'
],'public/css/plantilla.css')

.scripts([
    'resources/assets/js/jquery-3.4.1.min.js',
    'resources/assets/js/jquery.min.js',
    'resources/assets/js/bootstrap.bundle.min.js',
    'resources/assets/js/fastclick.js',
    'resources/assets/js/nprogress.js',
    'resources/assets/js/Chart.min.js',
    'resources/assets/js/jquery.sparkline.min.js',
    'resources/assets/js/gauge.min.js',
    'resources/assets/js/jquery.mCustomScrollbar.concat.min.js',
    'resources/assets/js/bootstrap-progressbar.min.js',
    'resources/assets/js/icheck.min.js',
    'resources/assets/js/skycons.js',
    'resources/assets/js/jquery.flot.js',
    'resources/assets/js/jquery.flot.pie.js',
    'resources/assets/js/jquery.flot.time.js',
    'resources/assets/js/jquery.flot.stack.js',
    'resources/assets/js/jquery.flot.resize.js',
    'resources/assets/js/jquery.flot.orderBars.js',
    'resources/assets/js/jquery.flot.spline.min.js',
    'resources/assets/js/curvedLines.js',
    'resources/assets/js/date.js',
    'resources/assets/js/jquery.vmap.js',
    'resources/assets/js/jquery.vmap.world.js',
    'resources/assets/js/jquery.vmap.sampledata.js',
    'resources/assets/js/moment.min.js',
    'resources/assets/js/daterangepicker.js',
    'resources/assets/js/bootstrap-wysiwyg.min.js',
    'resources/assets/js/jquery.hotkeys.js',
    'resources/assets/js/prettify.js',
    'resources/assets/js/jquery.tagsinput.js',
    'resources/assets/js/switchery.min.js',
    'resources/assets/js/select2.full.min.js',
    'resources/assets/js/parsley.min.js',
    'resources/assets/js/autosize.min.js',
    'resources/assets/js/jquery.autocomplete.min.js',
    'resources/assets/js/starrr.js',
    'resources/assets/js/custom.min.js',
    'resources/assets/js/core/main.js',
    'resources/assets/js/interaction/main.js',
    'resources/assets/js/daygrid/main.js',
    'resources/assets/js/timegrid/main.js',
    'resources/assets/js/all.min.js',
    'resources/assets/js/dropzone.min.js',
    'resources/assets/js/bootstrap-select.min.js',
    'resources/assets/js/sweetalert2.all.js',
    'resources/assets/js/jquery.dataTables.min.js',
    'resources/assets/js/dataTables.bootstrap.min.js',
    'resources/assets/js/dataTables.buttons.min.js',
    'resources/assets/js/buttons.bootstrap.min.js',
    'resources/assets/js/buttons.flash.min.js',
    'resources/assets/js/buttons.html5.min.js',
    'resources/assets/js/buttons.print.min.js',
    'resources/assets/js/dataTables.fixedHeader.min.js',
    'resources/assets/js/dataTables.keyTable.min.js',
    'resources/assets/js/dataTables.responsive.min.js',
    'resources/assets/js/responsive.bootstrap.js',
    'resources/assets/js/dataTables.scroller.min.js',
    'resources/assets/js/jszip.min.js',
    'resources/assets/js/pdfmake.min.js',
    'resources/assets/js/vfs_fonts.js'
], 'public/js/plantilla.js');
